// <auto-generated />
using DNP1_assignment.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace DNP1assignment.Migrations
{
    [DbContext(typeof(VIACinemaContext))]
    [Migration("20180521132604_test")]
    partial class test
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.3-rtm-10026")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DNP1_assignment.Models.Cinema", b =>
                {
                    b.Property<string>("Name")
                        .ValueGeneratedOnAdd();

                    b.HasKey("Name");

                    b.ToTable("Cinemas");
                });

            modelBuilder.Entity("DNP1_assignment.Models.Hall", b =>
                {
                    b.Property<string>("Name")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CinemaName");

                    b.Property<int?>("SeatsId");

                    b.HasKey("Name");

                    b.HasIndex("CinemaName");

                    b.HasIndex("SeatsId");

                    b.ToTable("Halls");
                });

            modelBuilder.Entity("DNP1_assignment.Models.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name")
                        .HasMaxLength(50);

                    b.Property<string>("description");

                    b.Property<int>("length");

                    b.Property<int>("miminalAge");

                    b.Property<string>("origin");

                    b.Property<DateTime>("releaseDate");

                    b.HasKey("Id");

                    b.ToTable("Movies");
                });

            modelBuilder.Entity("DNP1_assignment.Models.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.HasKey("Id");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("DNP1_assignment.Models.Performance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Date");

                    b.Property<string>("HallName");

                    b.Property<string>("Language");

                    b.Property<int?>("MovieId");

                    b.Property<string>("Subtitles");

                    b.HasKey("Id");

                    b.HasIndex("HallName");

                    b.HasIndex("MovieId")
                        .IsUnique()
                        .HasFilter("[MovieId] IS NOT NULL");

                    b.ToTable("Performances");
                });

            modelBuilder.Entity("DNP1_assignment.Models.Seat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("PaymentId");

                    b.Property<int?>("PerformanceId");

                    b.Property<int>("xPosition");

                    b.Property<int>("yPosition");

                    b.HasKey("Id");

                    b.HasIndex("PaymentId");

                    b.HasIndex("PerformanceId");

                    b.ToTable("Seats");
                });

            modelBuilder.Entity("DNP1_assignment.Models.Ticket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Discount");

                    b.Property<int?>("PerformanceId");

                    b.Property<int?>("SeatId");

                    b.Property<double>("price");

                    b.HasKey("Id");

                    b.HasIndex("PerformanceId");

                    b.HasIndex("SeatId");

                    b.ToTable("Tickets");
                });

            modelBuilder.Entity("DNP1_assignment.Models.Hall", b =>
                {
                    b.HasOne("DNP1_assignment.Models.Cinema", "Cinema")
                        .WithMany("Halls")
                        .HasForeignKey("CinemaName");

                    b.HasOne("DNP1_assignment.Models.Seat", "Seats")
                        .WithMany()
                        .HasForeignKey("SeatsId");
                });

            modelBuilder.Entity("DNP1_assignment.Models.Performance", b =>
                {
                    b.HasOne("DNP1_assignment.Models.Hall", "Hall")
                        .WithMany("Performances")
                        .HasForeignKey("HallName");

                    b.HasOne("DNP1_assignment.Models.Movie", "Movie")
                        .WithOne("performances")
                        .HasForeignKey("DNP1_assignment.Models.Performance", "MovieId");
                });

            modelBuilder.Entity("DNP1_assignment.Models.Seat", b =>
                {
                    b.HasOne("DNP1_assignment.Models.Payment", "Payment")
                        .WithMany()
                        .HasForeignKey("PaymentId");

                    b.HasOne("DNP1_assignment.Models.Performance", "Performance")
                        .WithMany()
                        .HasForeignKey("PerformanceId");
                });

            modelBuilder.Entity("DNP1_assignment.Models.Ticket", b =>
                {
                    b.HasOne("DNP1_assignment.Models.Performance")
                        .WithMany("Tickets")
                        .HasForeignKey("PerformanceId");

                    b.HasOne("DNP1_assignment.Models.Seat", "Seat")
                        .WithMany()
                        .HasForeignKey("SeatId");
                });
#pragma warning restore 612, 618
        }
    }
}
